### ISSUE TITLE
Make base_trace return spectrum per frequency instead of per bin

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#103]
Currently, the base_trace.get_frequency_spectrum() function return the spectrum in the units V/m/bin, which means that the values returned depend on the sampling rate. This is a bit confusing and can easily lead to mistakes.
I would suggest that we instead modify the base_trace class so that it return the spectrum as V/m/GHz to make it independent of the sampling rate.

**Comment by anelles** [comment]
I like this suggestion, especially after having long discussions at a previous ARIANNA publication regarding this. 
Would it make sense to also store units as a tag/string for those who don't know what the normalization is?

**Comment by cg-laser** [comment]
this would boil down to our fft normalization and would only need to be changed there. Currently it is normalized such that sum(trace**2) == sum(spectrum**2), i.e. norm == "ortho".
We can also get rid of this, then the energy fluence would be (deltaT * sum(trace**2) == deltaF * sum(trace**2))
If we normalize it to "per frequency" (always in default units which is currently GHz), the energy fluence would be deltaF*3 * sum*(spectrum**2) (???), because you would normalize the spectrum via spectrum /= deltaF (or /= sqrt(deltaF) beacuse the power is conserved?
This change would be fully backward compatible because everything is saved in the time domain. And I guess it would make sense. We need to make sure that all calculations in the frequecy domain still yield the same result.

**Comment by christophwelling** [comment]
We though about putting it in the get_frequency_spectrum method of the base_trace, but your suggestion seems better.
I don't think tagging the units is necessary. The whole point of our units system is that you don't have to know what the base units in NuRadioReco are. So I think it should be be enough to point out that the spectrum is voltage/frequency in the docstring.
