### ISSUE TITLE
Default particle type in station class

### ISSUE THREAD

**Issue by fschlueter** [nu-radio/NuRadioReco#110]
Hi guys,
it might be a design decision but it caused some trouble for me, this is why i am reporting this. 
In the base station class the particle type is initialized with
        self._particle_type = 'nu'
this forces you to run the cosmicRayIdentifier. Otherwise you transform the signal as a cr station and re transform it as a neutrino station which has effects on the applied zenith angle.
I think a more safe solution would be to initialize the stations without any type and raise an error in the set_is_cosmic_ray / set_is_neutrino function when the type is not initialized.
Cheers

**Comment by anelles** [comment]
Thanks for raising this issue. Indeed, I think this is not consistently treated in NuRadioReco at the moment, as we developed this for ARIANNA first, where there is only one special casing for neutrinos and air showers. This will be more complex for future detectors. I think @christophwelling and I saw a similar inconsistentcy today, when dealing with the refraction into the ice. 
Please go ahead and make a pull request, if you have a suggestion, otherwise, we will get to that once everyone is back from summer holdidays.
