### ISSUE TITLE
Transition to Python 3

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioReco#34]
**Describe the issue**
Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. 

**Expected behavior**
NuRadioReco needs to run with Python 3.

**Comment by cg-laser** [comment]
the critical part is the io, because of the different string representation.
The rest could be coded p2/3 compatible: http://python-future.org/compatible_idioms.html

The problem with the transition is the following: snowshovel only compiles with root 5, root 5 only compiles with python 2.... Hence, when we move to p3 we might not be able to read our data...

**Comment by anelles** [comment]
Well, snowshovel hardly compiles on the new systems anyway. So this is going to be a problem anyhow rather sooner than later ... ROOT 5 support has been discontinued for a while already.
I have no good solution to this, but we cannot keep NuRadioReco at an old version if we want to use it also for other purposes than ARIANNA.

**Comment by cg-laser** [comment]
I agree, but just moving to p3 exclusively is also not an option at the moment. The best would be if we could write all code p2 and p3 compatible which should be possible with `from __future__ import ...`
