### ISSUE TITLE
Handling GPS seconds

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#58]
We decided to store the station time as GPS seconds. However, doing this in native python 2 is a bit tricky. Python datetime only supports UTC (which has leap seconds). In principle it is possible to calculate GPS time from this, but it is a bit fiddly and easy to make mistakes. It is a bit better in python 3, but still not great.

How about we use the time functions from astropy(http://docs.astropy.org/en/stable/time/index.html) instead? These would just handle all this for us. It may even be a good idea to just store the astropy.Time object itself. 
It would of course mean introducing a new dependency, but I think it is worth it. Are there any objections?

**Comment by cg-laser** [comment]
I had a look at the astropy time class. Looks very good to me. It can everything we want and is so much better than datetime. Especially the super easy gps and unix second conversion is awesome. And the it keeps nanosecond precision over the time of the universe is great!

I was just hesitant to add a new dependency. But adding astropy makes sense. It is anyway a standard package in our field and we might think of using it in the future for future extensions. E.g. the conversion of local coordinates to Equatorial. 

This will likely be a larger change to NuRadioReco, not difficult but the times are used in several modules. We should be able to implement the dataformat backward compatible. Check if the type of the object in the data file is a datetime object or an astropy object.

**Comment by anelles** [comment]
@christophwelling is anyway working on a major overhaul of our treatment of the timing. So this question is just a by-product of the ongoing discussing of how to handle timing in general. This has been done very inconsistently so far. All this rolling of traces in transformations, triggers, and window cutters. 

As opposed to the astropy units, I think that the time handling is very nice and suits our goals. Since it is 'just' a Python module, I think this is a reasonable dependency to have. Much less work than for example having to checkout radiotools.

**Comment by cg-laser** [comment]
Just wanted to mention that the treatment of times and when to roll a trace and when to just adjust the trace start time has already thought through carefully: https://github.com/nu-radio/NuRadioReco/wiki/Times We should discuss this early on if this logic should be changed. 
What is not handled yet is the time of efields if they are not associated with just one channel.

**Comment by christophwelling** [comment]
I am not changing the logic, it just isn't properly implemented. In many places, the trace_start_time is not changed when the trace is rolled. I guess this happened when we removed the trace_start_time from the station?
Also, when we reconstructed the electric fields, we did not pay attention on the timings between channels and efields, so I am fixing that too.
So that documentation is still valid, except we now change the channel trace_start_time instead  of the station.

**Comment by cg-laser** [comment]
ok cool, just wanted to check. 

This is probably getting off topic but: The trace start time should not be altered when a trace is rolled. Otherwise you correct for it twice. And for some cases  the time shift is frequency dependent (amp deconvolution) so there is no way of correcting it via the trace start time.

**Comment by christophwelling** [comment]
I would say that depends on the module. For the channelLengthAdjuster and the trigger simulation we want to change both, otherwise the timing of the channel traces changes relative to the E-fields.
For things like the hardwareResponseIncorporator I agree, we only want to either change the trace_start_time or roll the trace.
I will update the documentation on the timings once my changes are merged.

**Comment by cg-laser** [comment]
I agree, but the first two cases don't roll the trace. They just cut/extend the trace ;-) So these modules should not change the time. Thanks for checking all these things.

**Comment by christophwelling** [comment]
Sometimes they do. For example if the pulse is at the very end of the trace and the trace needs to be shortened, they both will roll the pulse to the front and then cut the trace.

**Comment by cg-laser** [comment]
I implemented it such so that the algorithm always works, but for simulated signals this should never happen. The logic is that the simulated trace needs to be long enough (zeros at the beginning and end) the the pulse will never be near the beginning and the end. 
What can happen is that one triggers on noise where the maximum can then be at any position.

**Comment by christophwelling** [comment]
Okay, so astropy it is.
