### ISSUE TITLE
Fix documentation with Sphinx

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioReco#71]
The documentation sort of builds, but it finds many old modules and it needs to be cleaned up.

**Comment by anelles** [comment]
@cg-laser, I tried to look into this, but since you made the first iteration, I am not quite sure how to update what we have. Can you have a look? I am happy to contribute to beautifying, but I would like an updated version first, please.

**Comment by cg-laser** [comment]
I wondered if it doesn't make more sense to set this up as github page. I'm not sure how much of the current stuff can be used then. Therefore, I'm hesitant to put too much work in fixing the doc right now without first exploring this option.

**Comment by anelles** [comment]
From as far as I understand, you need a second repo where you use exactly what we have in the folder now. However, I couldn't reproduce the stuff we have in the folder now, so I am punting this back to you ;)

**Comment by cg-laser** [comment]
I found a good tutorial: https://daler.github.io/sphinxdoc-test/includeme.html

I also looked into the current documentation. The *.rst files are just outdated. I auto-generated them a year ago. Since then many module names changes or moved. We would either need to start from scratch again, or manually edit all the rst files.

**Comment by anelles** [comment]
As discussed at DESY: @cg-laser, if you run the auto-generate again, I will look into beautification.
