### ISSUE TITLE
automatically open file in eventbrowser

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioReco#78]
**Describe the issue**
When the eventbrowser is started from the commandline, only a folder can be specified.

**Expected behavior**
When a file is specified, directly open the file. 

In addition, maybe we could automatically open a window showing the event browser? I think one can start a browser window without any addressbar, bookmarks etc. 

Can we make the eventbrowser an executable? And the executable is automatically installed such that it is in $PATH. Then users can just execute "NuRadioRecoBrowser" or "NRRBrowser" from the command line.

**Comment by cg-laser** [comment]
its seems that there is a nice python interface to the browser: https://www.codevoila.com/post/45/open-web-browser-window-or-new-tab-with-python but it doesn't work for me :-(

**Comment by christophwelling** [comment]
I fixed the first two issues on the issues_77_78 branch. To open the browser window, I used the interface you linked to (worked for me), so can you see if it works for you? I decided to make this an optional, so to automatically open a browser window type python index.py /path/to/file --open_window. I imagine having this always on can easily get annoying. It also required turning the debug off, otherwise 2 browser windows will be opened. As far as I can tell that is an issue with dash itself.

**Comment by cg-laser** [comment]
great! Works for me. Not sure what I did wrong. 

One enhancement could be to just open a bare browser window. At least for me it opens a new tab in Chrome. But I think it is good enough for now.
